sudo: required
language: go
go:
  - 1.9.x
  - 1.10.x
services:
  - docker

before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - dep ensure -add github.com/golangci/golangci-lint/cmd/golangci-lint
  - dep ensure
  - go install ./vendor/github.com/golangci/golangci-lint/cmd/golangci-lint

script:
  - docker -v
  - golangci-lint run
  - go test -v -race ./...